"""delete users cascade

Revision ID: 0643d9dba546
Revises: 29bfd6a42512
Create Date: 2025-05-07 16:44:02.977628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0643d9dba546'
down_revision: Union[str, None] = '29bfd6a42512'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_added_by_user_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'users', ['added_by_user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_added_by_user_id_fkey', 'users', 'users', ['added_by_user_id'], ['id'])
    # ### end Alembic commands ###
