"""add added_by to users

Revision ID: 29bfd6a42512
Revises: d45265e3872f
Create Date: 2025-05-06 14:02:57.323742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29bfd6a42512'
down_revision: Union[str, None] = 'd45265e3872f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('template_variables')
    op.drop_table('templates')
    op.create_unique_constraint(None, 'companies', ['id'])
    op.add_column('users', sa.Column('added_by_user_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'users', ['id'])
    op.create_foreign_key(None, 'users', 'users', ['added_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'added_by_user_id')
    op.drop_constraint(None, 'companies', type_='unique')
    op.create_table('templates',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('templates_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='templates_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('template_variables',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('description', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('template_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], name='template_variables_template_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='template_variables_pkey')
    )
    # ### end Alembic commands ###
